version: "3.4"

services:
  nginx:
    image: nginx:1.12
    container_name: nginx
    volumes:
      - .platform/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_files:/var/www/tutorlio/static/
    ports:
      - "80:80"
    restart: always

  django:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    container_name: apps
    expose:
      - "8000"
    command: /start
    volumes:
      - static_files:/usr/src/apps/staticfiles
      - .:/apps:z
    restart: always

volumes:
  static_files:
