#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

rm -rf /app/static/*
python manage.py collectstatic --noinput
python manage.py migrate
python manage.py runserver_plus 0.0.0.0:8000 &

wait -n
exit $?
