#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


rm -rf /app/staticfiles/*
python manage.py collectstatic --noinput
python manage.py migrate

python manage.py runserver 0.0.0.0:8000 &

wait -n
exit $?
